common:
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  seed: 42

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: auroc
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 5
  patience: 10

dataset:
  data_format: meds
  data: ???
  label: true
  vocab_size: 28996
  pad_token_id: 0
  sep_token_id: 102
  dummy_token_id: 101
  ignore_index: -100

  num_workers: 6
  batch_size: 16
  train_subset: "train"
  valid_subset: "tuning"
  test_subset: "held_out"

distributed_training:
  distributed_world_size: 1
  find_unused_parameters: False

criterion:
  _name: binary_cross_entropy
  task_names:
    - mortality
  num_labels:
    - 1

optimization:
  max_epoch: 100
  lr: 1e-4

model:
  _name: genhpf_predictor

  structure: hierarchical
  embedding_method: text
